# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Macrarcli < Formula
  desc "Extract RAR archives directly — pure-Go, no unrar required"
  homepage "https://github.com/ongtungduong/macrarcli"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ongtungduong/macrarcli/releases/download/v0.3.0/macrarcli_darwin_amd64.tar.gz"
      sha256 "202a60044222313ebd625d827776b0831cef5a690f74d64555246504d431efc2"

      define_method(:install) do
        bin.install "macrarcli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ongtungduong/macrarcli/releases/download/v0.3.0/macrarcli_darwin_arm64.tar.gz"
      sha256 "baa6bb26a12170fe0be93f5c986f0d15bdb6d71aabbe30424166f2347cf3e5db"

      define_method(:install) do
        bin.install "macrarcli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ongtungduong/macrarcli/releases/download/v0.3.0/macrarcli_linux_amd64.tar.gz"
      sha256 "a591d87b3c0ec3c36b89f24ba64ea0ecdfbf357efe0ad1167b55e0d2ce17a45e"
      define_method(:install) do
        bin.install "macrarcli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ongtungduong/macrarcli/releases/download/v0.3.0/macrarcli_linux_arm64.tar.gz"
      sha256 "dedf495de8682955b9364cb7904522aab9ecc383bf192f51d8fb2ef54cf07bad"
      define_method(:install) do
        bin.install "macrarcli"
      end
    end
  end

  test do
    system "#{bin}/macrarcli", "--version"
  end
end
