# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rar2zip < Formula
  desc "Convert RAR archives to ZIP — pure-Go, no unrar required"
  homepage "https://github.com/ongtungduong/rar2zip"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ongtungduong/rar2zip/releases/download/v0.1.0/rar2zip_darwin_amd64.tar.gz"
      sha256 "8ba247c0354459b3221fa681c3cb425dadbd5314b7f6264d40a466e04fc34fa1"

      define_method(:install) do
        bin.install "rar2zip"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ongtungduong/rar2zip/releases/download/v0.1.0/rar2zip_darwin_arm64.tar.gz"
      sha256 "025c197a94687a32eab1b2167ba606146ddd20f4db7d3a8b0f80ac1272f251f8"

      define_method(:install) do
        bin.install "rar2zip"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ongtungduong/rar2zip/releases/download/v0.1.0/rar2zip_linux_amd64.tar.gz"
      sha256 "add85b221440d177e4cddacd969df6ffde2c79ff79b9c88c54d4486a45047331"
      define_method(:install) do
        bin.install "rar2zip"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ongtungduong/rar2zip/releases/download/v0.1.0/rar2zip_linux_arm64.tar.gz"
      sha256 "6f9b584f0dad2c8b3be889459b6ed84255914a4b7e0fe4cc6623eb6ad9d36bc8"
      define_method(:install) do
        bin.install "rar2zip"
      end
    end
  end

  test do
    system "#{bin}/rar2zip", "--version"
  end
end
