# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rar2zip < Formula
  desc "Convert RAR archives to ZIP — pure-Go, no unrar required"
  homepage "https://github.com/ongtungduong/rar2zip"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ongtungduong/rar2zip/releases/download/v0.2.1/rar2zip_darwin_amd64.tar.gz"
      sha256 "2070592ac3c0b8a9afb4c94190398339ba639980f7f2147453a2f188db9a80f5"

      define_method(:install) do
        bin.install "rar2zip"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ongtungduong/rar2zip/releases/download/v0.2.1/rar2zip_darwin_arm64.tar.gz"
      sha256 "b2810a70cb35e03d97b22bd8150de8f796bfd804c12da872da3240b808f75e2d"

      define_method(:install) do
        bin.install "rar2zip"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ongtungduong/rar2zip/releases/download/v0.2.1/rar2zip_linux_amd64.tar.gz"
      sha256 "1c0b1d554456a702bee275b093df175469b635ed744e43fc1073a8a739a8938c"
      define_method(:install) do
        bin.install "rar2zip"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ongtungduong/rar2zip/releases/download/v0.2.1/rar2zip_linux_arm64.tar.gz"
      sha256 "839fd7cf859870dfe4011d860b4bbc5881032ef04bd1dc9c790f0cd773607bd9"
      define_method(:install) do
        bin.install "rar2zip"
      end
    end
  end

  test do
    system "#{bin}/rar2zip", "--version"
  end
end
